safe: True
port: 4001
base-url:    /

gems:
  - jekyll-sitemap

source:      ./src/site
destination: ./_gh_pages
plugins:     ./src/site/_plugins

future:      true
lsi:         false
highlighter: true
permalink:   blog/:title

rdiscount:
  extensions: []

# Custom vars
current_version:  0.1.2
site: /
blog: /blog/
