safe: True
port: 4002
base-url:    /

gems:
  - jekyll-sitemap

source:      ./source/site
destination: ./_gh_pages
plugins:     ./source/site/_plugins

future:      true
lsi:         false
highlighter: true
permalink:   blog/:title

rdiscount:
  extensions: []

# Custom vars
current_version:  0.1.3
site: https://unmodded.com
blog: /blog/
